
on:
  pull_request:
    types: [labeled]

jobs:    
  nuget-alpha:
    if: contains(github.event.issue.labels.*.name, 'Run Test') != true
    runs-on: ubuntu-latest
    name: Nuget PreRelease package check
    steps:
      - uses: actions/checkout@v2
      - uses: agoda-com/ga-nuget-alpha-detection@v1
        with:
          solution-file-full-path: 'nuget-alpha/ConsoleApp1.sln'