

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master      
    types: [labeled]

jobs:    
  nuget-alpha:
    if: contains(github.event.issue.labels.*.name, 'Run Test') != true
    runs-on: ubuntu-latest
    name: Nuget PreRelease package check
    steps:
      - uses: actions/checkout@v2
      - run: echo -e "Default \e[31mRed"
      - run: docker run -t mcr.microsoft.com/powershell:7.1.1-ubuntu-18.04 pwsh -Command 'Write-Host "Default \e[31mRed"'
      - run: docker run -t mcr.microsoft.com/powershell:7.1.1-ubuntu-18.04 pwsh -Command 'Write-Host "asdasd" -ForegroundColor Red'
      - uses: agoda-com/ga-nuget-alpha-detection@v1
        with:
          solution-file-full-path: 'nuget-alpha/ConsoleApp1.sln'
